### ISSUE TITLE
hmm why do you have no stars or forks but 18 watchers :(

### ISSUE THREAD

**Issue by chadfurman** [Esri/kubeutils#1]
I really like this project but I am scared to use it... noone has starred or forked it?  That just feels weird... there is another kubeutils package on google by a different author but it links to this repo, also, and so why would that be if there are no stars or forks? 

Weird...

**Comment by dmfenton** [comment]
Hi! There are 18 watchers because a bunch of people on our dev team are set to automatically watch projects when they are created. As for no forks or stars, that's because it's brand new. We had just a couple people working on it before we opened sourced it last week. I'm not surprised there are other kubeutils packages, it wasn't a very creative name, but this is the only package of that name on NPM.

**Comment by jgravois** [comment]
> I really like this project but I am scared to use it.

no one ever got fired for buying [IBM](https://en.wikipedia.org/wiki/Fear,_uncertainty_and_doubt#SCO_v._IBM) 😉
